// MTG keyword definitions used for hover tooltips in the AI Judge chat

export const MTG_KEYWORDS: Record<string, string> = {
  "lifelink":         "Damage dealt by this source also causes its controller to gain that much life.",
  "deathtouch":       "Any amount of damage this deals to a creature is enough to destroy it.",
  "trample":          "Excess damage over what would be lethal can be assigned to the defending player or planeswalker.",
  "haste":            "This creature can attack and activate tap abilities the turn it enters the battlefield.",
  "vigilance":        "Attacking does not cause this creature to tap.",
  "flash":            "You may cast this spell any time you could cast an instant.",
  "flying":           "This creature can only be blocked by creatures with flying or reach.",
  "reach":            "This creature can block creatures with flying.",
  "first strike":     "This creature deals its combat damage before creatures without first strike.",
  "double strike":    "This creature deals combat damage in both the first and regular combat damage steps.",
  "menace":           "This creature can't be blocked except by two or more creatures.",
  "hexproof":         "This permanent can't be the target of spells or abilities your opponents control.",
  "indestructible":   "Effects that say 'destroy' don't destroy this permanent. Lethal damage doesn't destroy it either.",
  "shroud":           "This permanent can't be the target of any spells or abilities, including yours.",
  "ward":             "Whenever this permanent becomes the target of an opponent's spell or ability, it's countered unless they pay the ward cost.",
  "proliferate":      "Choose any number of permanents/players with counters or poison, then put one more counter of each kind already there on them.",
  "commander damage": "If a commander has dealt 21 or more combat damage to a player over the course of the game, that player loses.",
  "commander tax":    "Each time a commander is cast from the command zone, it costs {2} more for each previous time it was cast from there.",
  "phasing":          "A phased-out permanent is treated as if it doesn't exist until it phases back in at the start of its controller's untap step.",
  "flashback":        "You may cast this card from your graveyard by paying its flashback cost. Then exile it.",
  "kicker":           "An optional additional cost you may pay when casting a spell that gives it additional benefits.",
  "morph":            "You may cast this card face-down as a 2/2 creature for {3}. Turn it face-up at any time for its morph cost.",
  "enrage":           "Triggers whenever this creature is dealt damage.",
  "storm":            "When you cast this spell, copy it for each spell cast before it this turn.",
  "infect":           "This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.",
  "toxic":            "Whenever this creature deals combat damage to a player, that player gets N poison counters.",
  "convoke":          "Each creature you tap while casting this spell pays for {1} or one mana of that creature's color.",
  "delve":            "You may exile cards from your graveyard to pay for the generic mana cost of this spell.",
  "escape":           "You may cast this card from your graveyard by exiling a certain number of other cards from your graveyard.",
  "exploit":          "When this creature enters the battlefield, you may sacrifice a creature.",
  "devotion":         "The number of mana symbols of a specific color among the mana costs of permanents you control.",
  "monarch":          "The monarch draws a card at the beginning of their end step. When a creature deals combat damage to the monarch, the damaging player becomes the monarch.",
  "initiative":       "The player with the initiative ventures into the Undercity at the beginning of their upkeep.",
  "city's blessing":  "A designation that a player gets when they control 10 or more permanents. It is checked as 'ascend.'",
  "day":              "The game is in daytime. If no spells are cast on a player's turn, it becomes night.",
  "night":            "The game is at nighttime. Day/Night creatures transform to their night faces.",
  "rad counter":      "A counter from the Fallout set. At the beginning of your precombat main phase, mill cards equal to your rad counters, then lose 1 life for each nonland milled.",
  "poison counter":   "A player with 10 or more poison counters loses the game.",
  "protection":       "Can't be damaged, enchanted, equipped, blocked, or targeted by anything with the specified quality.",
  "landfall":         "Triggers whenever a land enters the battlefield under your control.",
  "cascade":          "When you cast this spell, exile cards until you find one with lesser mana value, then cast it for free.",
  "cycling":          "Pay the cycling cost and discard this card: Draw a card.",
  "bestow":           "You may cast this as an Aura. If the enchanted creature leaves, this becomes a creature.",
  "mutate":           "Merge with a non-Human creature to create a merged permanent with combined abilities.",
  "foretell":         "During your turn, you may exile this card from your hand face-down for {2}. Cast it on a later turn for its foretell cost.",
  "boast":            "Activate only if this creature attacked this turn, and only once each turn.",
  "blitz":            "An alternative cost to cast the creature; it gains haste and 'when it dies, draw a card,' but it's sacrificed at the end of turn.",
};
