// Centralized localStorage key constants — import from here instead of using raw strings

export const STORAGE_KEYS = {
  GEMINI_KEY:      "nexus_judge_gemini_key",
  GEMINI_MODEL:    "nexus_judge_gemini_model",
  AI_CHAT:         "nexus_judge_ai_chat",
  AI_TAGS:         "nexus_judge_ai_tags",
  AI_RULINGS:      "nexus_judge_ai_rulings",
  PLAYER_NAMES:    "nexus_judge_player_names",
  PLAYERS:         "nexus_judge_players",
  PLAYER_COUNT:    "nexus_judge_player_count",
  STARTING_LIFE:   "nexus_judge_starting_life",
  LIFE_HISTORY:    "nexus_judge_life_history",
  ACTIVE_COUNTERS: "nexus_judge_active_counters",
  DAY_NIGHT:       "nexus_judge_day_night",
  TURN_PLAYERS:    "nexus_judge_turn_players",
  TURN_WINNER:     "nexus_judge_turn_winner",
  TURN_INDEX:      "nexus_judge_turn_index",
  TURN_ROLLOFFS:   "nexus_judge_turn_rolloffs",
  TURN_COLORS:     "nexus_judge_turn_colors",
  CARD_HISTORY:       "nexus_judge_card_history",
  SAVED_GAMES:        "nexus_judge_saved_games",
  AI_FAVORITES:       "nexus_judge_ai_favorites",
  SIDEBAR_COLLAPSED:  "nexus_judge_sidebar_collapsed",
  HISTORY_COLLAPSED:  "nexus_judge_history_collapsed",
  CONTROLS_COLLAPSED: "nexus_judge_controls_collapsed",
  THEME:              "nexus_judge_theme",
  ROOM_CODE:          "nexus_judge_room_code",
  ACCESS_CODE:        "nexus_judge_access_code",
} as const;
